// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owctgxnyaxykuvfuliby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93Y3RneG55YXh5a3V2ZnVsaWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2NTMxMjYsImV4cCI6MjA0OTIyOTEyNn0._5hG_ibps8KcoX8HHfZceeKL4TVHwqdalxVJKEMxZ_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);