// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xthhqmyrgaaounmzimrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0aGhxbXlyZ2Fhb3VubXppbXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODU5NjYsImV4cCI6MjA2MTA2MTk2Nn0.IwvyfA7O277B85CzHKnxvKexPj8Jl_eVGQwcOITYKVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);